### ISSUE TITLE
AttributeError: 'module' object has no attribute 'computation'

### ISSUE THREAD

**Issue by StrangeTcy** [nlml/np-to-tf-embeddings-visualiser#1]
Running `python example.py` on Ubuntu 16.04 with the latest libraries installed results in multiple errors:
```
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "example.py", line 18, in <module>
    from save_embeddings import save_embeddings
  File "/home/gabriel/np-to-tf-embeddings-visualiser/save_embeddings.py", line 12, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py", line 31, in <module>
    from tensorflow.contrib import distributions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distributions/__init__.py", line 33, in <module>
    from tensorflow.contrib.distributions.python.ops.estimator import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distributions/python/ops/estimator.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.head import _compute_weighted_loss
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/__init__.py", line 92, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/__init__.py", line 23, in <module>
    from tensorflow.contrib.learn.python.learn import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/__init__.py", line 25, in <module>
    from tensorflow.contrib.learn.python.learn import estimators
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/__init__.py", line 297, in <module>
    from tensorflow.contrib.learn.python.learn.estimators.dnn import DNNClassifier
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn.py", line 30, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import dnn_linear_combined
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/dnn_linear_combined.py", line 31, in <module>
    from tensorflow.contrib.learn.python.learn.estimators import estimator
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 49, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io import data_feeder
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/__init__.py", line 21, in <module>
    from tensorflow.contrib.learn.python.learn.learn_io.dask_io import extract_dask_data
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/learn_io/dask_io.py", line 26, in <module>
    import dask.dataframe as dd
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "/usr/local/lib/python2.7/dist-packages/dask/dataframe/core.py", line 38, in <module>
    pd.computation.expressions.set_use_numexpr(False)
AttributeError: 'module' object has no attribute 'computation'
```

This error has occured before, was probably fixed in dask > 0.15.3, but has probably re-occured in dask  0.17.1

**Comment by nlml** [comment]
Hmm, not sure what could be causing that. Might I suggest [this tool](https://github.com/lanpa/tensorboard-pytorch) as a more full-fledged alternative to my tool here.

**Comment by StrangeTcy** [comment]
Thanks; I'll look into that

**Comment by StrangeTcy** [comment]
Ok, it works if I explicitly run `python3 example.py`
